#! /bin/bash
#
# docker/makedist -- make all components from this repo via the docker containers
#                    defined in the docker directory.
#
# Usage: docker/makedist [--dist-dir=DIR] [python|angular]
#
# where:
#   --dist-dir=DIR     write component distributions to the given directory
#                      (instead of the default directory, dist)
#   angular            build all the available angular-based distributions
#
echo "############ makedist in docker  $@ "
prog=`basename $0`
execdir=`dirname $0`
[ "$execdir" = "" -o "$execdir" = "." ] && execdir=$PWD
export CODEDIR=`(cd $execdir/.. > /dev/null 2>&1; pwd)`
export DOCKERDIR=$execdir

exec $DOCKERDIR/run.sh build "$@"
